"""State definitions for the research agent."""
from typing import Annotated, TypedDict
from langgraph.graph.message import add_messages


class ResearchState(TypedDict):
    """State for the research agent."""
    # User's original query
    query: str

    # Chat messages (with tool calls and results)
    messages: Annotated[list, add_messages]

    # Research plan generated by the planner
    research_plan: list[str]

    # Search queries executed
    search_queries: list[str]

    # URLs that have been read
    read_urls: list[str]

    # Collected research findings
    findings: list[str]

    # Current iteration count
    iteration: int

    # Final synthesized report
    report: str

    # Status: planning, researching, synthesizing, done
    status: str
